name: Building Blocks

on: 
    workflow_dispatch:
jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
           - name: echo-hello
             run: echo "hello"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
           - name: Fail the build
             run: |
                echo "goodbye"
                exit 1
           - name :after-goodbye
             run :echo "after goodbye"
